name: stocks
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.0=py38_1001
  - argon2-cffi=20.1.0=py38haf1e3a3_1
  - async_generator=1.10=py_0
  - attrs=20.2.0=py_0
  - backcall=0.2.0=py_0
  - bleach=3.2.1=py_0
  - ca-certificates=2020.10.14=0
  - certifi=2020.6.20=py38_0
  - cffi=1.14.3=py38hed5b41f_0
  - dbus=1.13.18=h18a8e69_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py38_0
  - expat=2.2.10=hb1e8313_2
  - gettext=0.19.8.1=h15daf44_3
  - glib=2.66.1=h9bbe63b_0
  - icu=58.2=h0a44026_3
  - importlib-metadata=2.0.0=py_1
  - importlib_metadata=2.0.0=1
  - ipykernel=5.3.4=py38h5ca1d4c_0
  - ipython=7.18.1=py38h5ca1d4c_0
  - ipython_genutils=0.2.0=py38_0
  - ipywidgets=7.5.1=py_1
  - jedi=0.18.0=py38h50d1736_2
  - jpeg=9b=he5867d9_2
  - jsonschema=3.2.0=py_2
  - jupyter=1.0.0=py38_7
  - jupyter_client=6.1.7=py_0
  - jupyter_console=6.2.0=py_0
  - jupyter_core=4.6.3=py38_0
  - jupyterlab_pygments=0.1.2=py_0
  - libcxx=10.0.0=1
  - libedit=3.1.20191231=h1de35cc_1
  - libffi=3.3=hb1e8313_2
  - libiconv=1.16=h1de35cc_0
  - libpng=1.6.37=ha441bb4_0
  - libsodium=1.0.18=h1de35cc_0
  - markupsafe=1.1.1=py38h1de35cc_1
  - mistune=0.8.4=py38h1de35cc_1001
  - nbclient=0.5.1=py_0
  - nbconvert=6.0.7=py38_0
  - nbformat=5.0.8=py_0
  - ncurses=6.2=h0a44026_1
  - nest-asyncio=1.4.1=py_0
  - notebook=6.1.4=py38_0
  - openssl=1.1.1h=haf1e3a3_0
  - pandoc=2.11=h0dc7051_0
  - pandocfilters=1.4.2=py38_1
  - parso=0.8.0=py_0
  - pcre=8.44=hb1e8313_0
  - pexpect=4.8.0=py38_1
  - pickleshare=0.7.5=py38_1001
  - pip=20.2.4=py38_0
  - prometheus_client=0.8.0=py_0
  - prompt-toolkit=3.0.8=py_0
  - prompt_toolkit=3.0.8=0
  - ptyprocess=0.6.0=py38_0
  - pycparser=2.20=py_2
  - pygments=2.7.1=py_0
  - pyparsing=2.4.7=py_0
  - pyqt=5.9.2=py38h655552a_2
  - pyrsistent=0.17.3=py38haf1e3a3_0
  - python=3.8.5=h26836e1_1
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=1_cp38
  - pyzmq=19.0.2=py38hb1e8313_1
  - qt=5.9.7=h468cd18_1
  - qtconsole=4.7.7=py_0
  - qtpy=1.9.0=py_0
  - readline=8.0=h1de35cc_0
  - send2trash=1.5.0=py38_0
  - setuptools=50.3.0=py38h0dc7051_1
  - sip=4.19.8=py38h0a44026_0
  - six=1.15.0=py_0
  - sqlite=3.33.0=hffcf06c_0
  - terminado=0.9.1=py38_0
  - testpath=0.4.4=py_0
  - tk=8.6.10=hb0a8c7a_0
  - tornado=6.0.4=py38h1de35cc_1
  - traitlets=5.0.5=py_0
  - wcwidth=0.2.5=py_0
  - webencodings=0.5.1=py38_1
  - wheel=0.35.1=py_0
  - widgetsnbextension=3.5.1=py38_0
  - xz=5.2.5=h1de35cc_0
  - zeromq=4.3.3=hb1e8313_3
  - zipp=3.3.1=py_0
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - blis==0.7.4
    - catalogue==2.0.1
    - chardet==4.0.0
    - click==7.1.2
    - cycler==0.10.0
    - cymem==2.0.5
    - en-core-web-sm==3.0.0
    - future==0.18.2
    - gensim==3.8.3
    - idna==2.10
    - jinja2==2.11.3
    - joblib==1.0.1
    - jupyter-http-over-ws==0.0.8
    - kiwisolver==1.3.1
    - matplotlib==3.3.4
    - murmurhash==1.0.5
    - nltk==3.5
    - numpy==1.20.1
    - oauthlib==3.1.0
    - packaging==20.9
    - pandas==1.2.1
    - pathy==0.3.6
    - patsy==0.5.1
    - pillow==8.1.0
    - plotly==4.14.3
    - praw==7.1.4
    - prawcore==1.5.0
    - preshed==3.0.5
    - pydantic==1.7.3
    - pysocks==1.7.1
    - python-decouple==3.4
    - pytz==2021.1
    - regex==2020.11.13
    - requests==2.25.1
    - requests-oauthlib==1.3.0
    - retrying==1.3.3
    - scikit-learn==0.24.1
    - scipy==1.6.0
    - seaborn==0.11.1
    - smart-open==3.0.0
    - spacy==3.0.1
    - spacy-legacy==3.0.1
    - srsly==2.4.0
    - statsmodels==0.12.2
    - texthero==1.0.9
    - thinc==8.0.1
    - threadpoolctl==2.1.0
    - torch==1.7.1
    - torchaudio==0.7.2
    - torchvision==0.8.2
    - tqdm==4.56.2
    - tweepy==3.10.0
    - typer==0.3.2
    - typing-extensions==3.7.4.3
    - unidecode==1.2.0
    - update-checker==0.18.0
    - urllib3==1.26.3
    - vadersentiment==3.3.2
    - wasabi==0.8.2
    - websocket-client==0.57.0
    - wordcloud==1.8.1
prefix: /opt/anaconda3/envs/stocks
